# Generated by Django 3.0.7 on 2022-05-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, default='/media/default/avatar.png', max_length=1000, null=True, verbose_name='头像'),
        ),
    ]
