# Generated by Django 3.2.14 on 2022-07-25 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('staffId', models.IntegerField()),
                ('realname', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': '七鱼staff',
                'verbose_name_plural': '七鱼staff',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='名称')),
                ('ticketId', models.IntegerField(unique=True)),
                ('templateId', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
                ('staffId', models.IntegerField()),
                ('status', models.IntegerField(default=10, max_length=10)),
                ('appName', models.CharField(default=None, max_length=64)),
                ('holderId', models.IntegerField()),
                ('finish_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': '工单',
                'verbose_name_plural': '工单',
            },
        ),
    ]
