# Generated by Django 3.2.14 on 2022-07-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='staffId',
            field=models.CharField(max_length=128),
        ),
    ]
