# Generated by Django 3.2.14 on 2022-07-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0002_alter_ticket_staffid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='staffId',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='appName',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='finish_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='holderId',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(default=10, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='templateId',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
