# Generated by Django 3.2.14 on 2022-07-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0003_auto_20220725_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=64, verbose_name='名称'),
        ),
    ]
