# Generated by Django 3.2.14 on 2022-07-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0004_alter_ticket_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='holderId',
        ),
        migrations.AddField(
            model_name='ticket',
            name='holder',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
