# Generated by Django 3.2.14 on 2022-07-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0006_quality_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='quality_status',
            field=models.CharField(default='未质检', max_length=32, null=True),
        ),
    ]
