# Generated by Django 3.2.14 on 2022-07-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0007_ticket_quality_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quality',
            name='forbiddance',
        ),
        migrations.RemoveField(
            model_name='quality',
            name='forbiddance_score',
        ),
        migrations.AddField(
            model_name='quality',
            name='forbiddance_a',
            field=models.CharField(default=None, max_length=36, null=True, verbose_name='禁止一类'),
        ),
        migrations.AddField(
            model_name='quality',
            name='forbiddance_b',
            field=models.CharField(default=None, max_length=36, null=True, verbose_name='禁止二类'),
        ),
        migrations.AddField(
            model_name='quality',
            name='inspect_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='质检时间'),
        ),
        migrations.AddField(
            model_name='quality',
            name='inspector',
            field=models.CharField(default=None, max_length=36, null=True, verbose_name='质检人'),
        ),
        migrations.AddField(
            model_name='quality',
            name='kefu',
            field=models.CharField(default=None, max_length=36, null=True, verbose_name='客服'),
        ),
        migrations.AddField(
            model_name='quality',
            name='score',
            field=models.IntegerField(default=None, null=True, verbose_name='质检结果'),
        ),
        migrations.AlterField(
            model_name='quality',
            name='response',
            field=models.IntegerField(verbose_name='对用户的感谢做出回应'),
        ),
        migrations.AlterField(
            model_name='quality',
            name='session',
            field=models.IntegerField(default=None, null=True, verbose_name='会话ID'),
        ),
    ]
