# Generated by Django 3.2.14 on 2022-07-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0008_auto_20220726_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quality',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='quality',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='quality',
            name='update_time',
        ),
        migrations.AlterField(
            model_name='quality',
            name='session',
            field=models.CharField(default=None, max_length=24, null=True, verbose_name='会话ID'),
        ),
    ]
