# Generated by Django 3.2.14 on 2022-07-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0009_auto_20220726_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='kefu',
            field=models.CharField(default=None, max_length=36, null=True, verbose_name='接待客服'),
        ),
    ]
