# Generated by Django 3.2.14 on 2022-07-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0010_alter_quality_kefu'),
    ]

    operations = [
        migrations.AddField(
            model_name='quality',
            name='comment',
            field=models.TextField(default=None, null=True, verbose_name='评语'),
        ),
    ]
