# Generated by Django 3.2.14 on 2022-07-27 09:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0011_quality_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quality',
            name='ticket',
        ),
        migrations.AddField(
            model_name='ticket',
            name='accuracy',
            field=models.IntegerField(default=None, null=True, verbose_name='准确性'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='basic_norm',
            field=models.IntegerField(default=None, null=True, verbose_name='基本规范'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='comment',
            field=models.TextField(default=None, null=True, verbose_name='评语'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='desire',
            field=models.IntegerField(default=None, null=True, verbose_name='帮助意愿'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='expression',
            field=models.IntegerField(default=None, null=True, verbose_name='表达能力'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='forbiddance_a',
            field=models.CharField(default=None, max_length=36, null=True, verbose_name='禁止一类'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='forbiddance_b',
            field=models.CharField(default=None, max_length=36, null=True, verbose_name='禁止二类'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='inspect_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='质检时间'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='inspector',
            field=models.CharField(default=None, max_length=36, null=True, verbose_name='质检人'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='integrity',
            field=models.IntegerField(default=None, null=True, verbose_name='完整性'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='negative_feedback',
            field=models.IntegerField(default=None, null=True, verbose_name='非常不满意'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='response',
            field=models.IntegerField(default=None, null=True, verbose_name='对用户的感谢做出回应'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='score',
            field=models.IntegerField(default=None, null=True, verbose_name='质检结果'),
        ),
        migrations.CreateModel(
            name='Recheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('comment', models.TextField(default=None, null=True, verbose_name='评语')),
                ('reason', models.TextField(default=None, null=True, verbose_name='理由')),
                ('ticket', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qc.ticket')),
            ],
            options={
                'verbose_name': '复检',
                'verbose_name_plural': '复检',
            },
        ),
        migrations.CreateModel(
            name='Qualitycase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('comment', models.TextField(default=None, null=True, verbose_name='测评')),
                ('status', models.CharField(default='待审核', max_length=32)),
                ('problem', models.CharField(default=None, max_length=64)),
                ('user', models.CharField(max_length=32)),
                ('ticket', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qc.ticket')),
            ],
            options={
                'verbose_name': '案例',
                'verbose_name_plural': '案例',
            },
        ),
    ]
