# Generated by Django 3.2.14 on 2022-07-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0012_auto_20220727_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='quality',
            name='quality_status',
            field=models.CharField(default='已质检', max_length=32, null=True),
        ),
    ]
