# Generated by Django 3.2.14 on 2022-07-27 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0013_quality_quality_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualitycase',
            name='problem',
        ),
        migrations.AddField(
            model_name='quality',
            name='problem',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name='严重问题'),
        ),
        migrations.AddField(
            model_name='qualitycase',
            name='quality',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qc.quality'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='problem',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name='严重问题'),
        ),
    ]
