# Generated by Django 3.2.14 on 2022-07-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0014_auto_20220727_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='problem',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='严重问题'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='problem',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='严重问题'),
        ),
    ]
