# Generated by Django 3.2.14 on 2022-07-28 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0016_alter_ticket_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recheck',
            name='quality',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qc.quality'),
        ),
        migrations.AlterField(
            model_name='qualitycase',
            name='user',
            field=models.CharField(max_length=32, verbose_name='申请人'),
        ),
    ]
