# Generated by Django 3.2.14 on 2022-07-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0017_auto_20220728_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='recheck',
            name='status',
            field=models.CharField(default='待审核', max_length=32),
        ),
    ]
