# Generated by Django 3.2.14 on 2022-07-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0018_recheck_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recheck',
            name='user',
            field=models.CharField(default='', max_length=32, verbose_name='申请人'),
            preserve_default=False,
        ),
    ]
