# Generated by Django 3.2.14 on 2022-08-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0021_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/%Y/%m/%d')),
                ('name', models.CharField(default='', max_length=128)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
    ]
