# Generated by Django 3.2.14 on 2022-08-02 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0022_auto_20220802_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='app_name',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='author',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='is_top',
        ),
    ]
