# Generated by Django 3.2.14 on 2022-08-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0023_auto_20220802_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='recheck',
            name='handler',
            field=models.CharField(default='', max_length=32, verbose_name='质检人'),
            preserve_default=False,
        ),
    ]
