# Generated by Django 3.2.14 on 2022-08-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0024_recheck_handler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recheck',
            name='handler',
            field=models.CharField(default=None, max_length=32, null=True, verbose_name='处理人'),
        ),
    ]
