# Generated by Django 3.2.14 on 2022-08-09 15:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0025_alter_recheck_handler'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('status', models.CharField(default='待审核', max_length=32)),
                ('comment', models.TextField(default=None, null=True, verbose_name='评语')),
                ('reason', models.TextField(default=None, null=True, verbose_name='理由')),
                ('user', models.CharField(max_length=32, verbose_name='申请人')),
                ('handler', models.CharField(default=None, max_length=32, null=True, verbose_name='处理人')),
                ('quality', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qc.quality')),
                ('ticket', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qc.ticket')),
            ],
            options={
                'verbose_name': '复检',
                'verbose_name_plural': '复检',
            },
        ),
    ]
