# Generated by Django 3.2.14 on 2022-08-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0028_auto_20220810_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='accuracy',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='准确性'),
        ),
        migrations.AlterField(
            model_name='quality',
            name='basic_norm',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='基本规范'),
        ),
        migrations.AlterField(
            model_name='quality',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='评语'),
        ),
        migrations.AlterField(
            model_name='quality',
            name='desire',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='帮助意愿'),
        ),
        migrations.AlterField(
            model_name='quality',
            name='expression',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='表达能力'),
        ),
        migrations.AlterField(
            model_name='quality',
            name='finish_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='会话结束时间'),
        ),
        migrations.AlterField(
            model_name='quality',
            name='forbiddance_a',
            field=models.CharField(blank=True, default=None, max_length=36, null=True, verbose_name='禁止一类'),
        ),
        migrations.AlterField(
            model_name='quality',
            name='forbiddance_b',
            field=models.CharField(blank=True, default=None, max_length=36, null=True, verbose_name='禁止二类'),
        ),
        migrations.AlterField(
            model_name='quality',
            name='inspect_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='质检时间'),
        ),
        migrations.AlterField(
            model_name='quality',
            name='integrity',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='完整性'),
        ),
        migrations.AlterField(
            model_name='quality',
            name='kefu',
            field=models.CharField(blank=True, default=None, max_length=36, null=True, verbose_name='接待客服'),
        ),
        migrations.AlterField(
            model_name='quality',
            name='negative_feedback',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='非常不满意'),
        ),
        migrations.AlterField(
            model_name='quality',
            name='quality_status',
            field=models.CharField(blank=True, default='已质检', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='quality',
            name='response',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='对用户的感谢做出回应'),
        ),
        migrations.AlterField(
            model_name='quality',
            name='score',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='质检结果'),
        ),
        migrations.AlterField(
            model_name='quality',
            name='start_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='会话开始时间'),
        ),
    ]
