# Generated by Django 3.2.14 on 2022-08-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0029_auto_20220810_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='quality_status',
            field=models.CharField(blank=True, default='未质检', max_length=32, null=True),
        ),
    ]
