# Generated by Django 3.2.14 on 2022-08-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0030_alter_quality_quality_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='quality_status',
            field=models.CharField(blank=True, default='待质检', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='quality_status',
            field=models.CharField(default='待质检', max_length=32, null=True),
        ),
    ]
