# Generated by Django 3.2.14 on 2022-08-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0031_auto_20220810_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='forbiddance_a',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='禁止一类'),
        ),
        migrations.AlterField(
            model_name='quality',
            name='forbiddance_b',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='禁止二类'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='forbiddance_a',
            field=models.IntegerField(default=None, null=True, verbose_name='禁止一类'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='forbiddance_b',
            field=models.IntegerField(default=None, null=True, verbose_name='禁止二类'),
        ),
    ]
