# Generated by Django 3.2.14 on 2022-08-10 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0032_auto_20220810_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='quality',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='quality',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记'),
        ),
        migrations.AddField(
            model_name='quality',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间'),
        ),
    ]
