# Generated by Django 3.2.14 on 2022-08-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0033_auto_20220810_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='accuracy',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='准确性'),
        ),
        migrations.AlterField(
            model_name='quality',
            name='basic_norm',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='基本规范'),
        ),
        migrations.AlterField(
            model_name='quality',
            name='desire',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='帮助意愿'),
        ),
        migrations.AlterField(
            model_name='quality',
            name='expression',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='表达能力'),
        ),
        migrations.AlterField(
            model_name='quality',
            name='forbiddance_a',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='禁止一类'),
        ),
        migrations.AlterField(
            model_name='quality',
            name='forbiddance_b',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='禁止二类'),
        ),
        migrations.AlterField(
            model_name='quality',
            name='integrity',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='完整性'),
        ),
        migrations.AlterField(
            model_name='quality',
            name='negative_feedback',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='非常不满意'),
        ),
        migrations.AlterField(
            model_name='quality',
            name='response',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='对用户的感谢做出回应'),
        ),
        migrations.AlterField(
            model_name='quality',
            name='score',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='质检结果'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='accuracy',
            field=models.FloatField(default=None, null=True, verbose_name='准确性'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='basic_norm',
            field=models.FloatField(default=None, null=True, verbose_name='基本规范'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='desire',
            field=models.FloatField(default=None, null=True, verbose_name='帮助意愿'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expression',
            field=models.FloatField(default=None, null=True, verbose_name='表达能力'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='forbiddance_a',
            field=models.FloatField(default=None, null=True, verbose_name='禁止一类'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='forbiddance_b',
            field=models.FloatField(default=None, null=True, verbose_name='禁止二类'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='integrity',
            field=models.FloatField(default=None, null=True, verbose_name='完整性'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='negative_feedback',
            field=models.FloatField(default=None, null=True, verbose_name='非常不满意'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='response',
            field=models.FloatField(default=None, null=True, verbose_name='对用户的感谢做出回应'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='score',
            field=models.FloatField(default=None, null=True, verbose_name='质检结果'),
        ),
    ]
